### ISSUE TITLE
Cannot open load GitQlientPlugin

### ISSUE THREAD

**Issue by OrkunTokdemir** [francescmm/GitQlientPlugin#12]
I could not load GitQlientPlugin on latest qtcreator. Qtcreator sends error message at the beginning. 

![image](https://user-images.githubusercontent.com/21346859/83875858-86d3e280-a740-11ea-9276-a34f7eb30ab4.png)

My qtcreator version is  4.12.2
![image](https://user-images.githubusercontent.com/21346859/83876170-137ea080-a741-11ea-8c9c-92cc19661388.png)
I guess other plugin versions do not match with GitQlientPlugin

**Comment by francescmaestre** [comment]
No I'm sorry but they have to match.

Good news are that I'm going to create the plug-in this weekend since I've been really busy lately.

**Comment by francescmaestre** [comment]
Hi @OrkunTokdemir , please find the release in here: https://github.com/francescmm/GitQlientPlugin/releases/tag/v1.2.0

**Comment by OrkunTokdemir** [comment]
@francescmm  thnx for your effort :)
