### ISSUE TITLE
GitLab Config, Token does not work.

### ISSUE THREAD

**Issue by isgursoy** [francescmm/GitQlientPlugin#13]
I am getting: "Error transferring https://gitlab.com/api/v4/user/repos - server replied: Not Found"
Using username or username@gitlab.com form does not change the result.

Does it work for you @francescmm ?

**Comment by francescmaestre** [comment]
Hi @isgursoy I've fixed it now. Try to update the submodule that is the actual app code.

Remember that master is under development, but I'll release the new version next week :smile:

**Comment by francescmaestre** [comment]
@isgursoy if you see any other error, please report it in https://github.com/francescmm/GitQlient repo! Thanks!

**Comment by isgursoy** [comment]
> Hi @isgursoy I've fixed it now. Try to update the submodule that is the actual app code.
> 
> Remember that master is under development, but I'll release the new version next week

Thanks, yes it works now. I am pulling and recompiling GitQlient every morning.

> @isgursoy if you see any other error, please report it in https://github.com/francescmm/GitQlient repo! Thanks!

Of course. Thank you again.
