### ISSUE TITLE
Build for new QtCreator

### ISSUE THREAD

**Issue by foxtrot75** [francescmm/GitQlientPlugin#14]
Please, build plugin for new QtCreator.

![image](https://user-images.githubusercontent.com/59334095/104576791-b600e980-5669-11eb-8742-cf352051b404.png)

**Comment by isgursoy** [comment]
to be able to compile plugin with recent Qt Creator and GitQlient versions you need these modifications:
- add `QT       += webenginewidgets` in GitQlientPlugin.pro
- Replace `Core::Id` class to `Utils::Id` in GitQlientPlugin.h and corresponding cpp file.
-  Also in GitQlientMode ctor:
``` 
  setWidget(mGitImpl = new GitQlient());
   mGitImpl->setArgumentsPostInit({ "-noLog" });

   mGitImpl->setObjectName("mainWindow");

/*   connect(mGitImpl, &GitQlient::signalEditDocument, [](const QString &fileName, int row, int col) {
      Core::EditorManager::instance()->openEditorAt(fileName, row, col);
   })*/;
```

Ubuntu 20.04, Qt 5.15.2, Qt Creator 4.15
[libGitQlientPlugin.so.zip](https://github.com/francescmm/GitQlientPlugin/files/6431621/libGitQlientPlugin.so.zip)

**Comment by isgursoy** [comment]
In case of the Github crash, first start Qt Creator from the terminal to see details, if you notice the "Could not find QtWebEngineProcess" line then the solution is putting webengine libraries under qtc/lib/Qt.

For example for Qt Creator 4.15 and 5.15.2 take following files from 5.15.2/gcc_64/lib and put under qtc/lib/Qt/lib:

```'/opt/qtc/415/lib/Qt/lib/libQt5WebEngine.la' 
'/opt/qtc/415/lib/Qt/lib/libQt5WebEngine.prl'
'/opt/qtc/415/lib/Qt/lib/libQt5WebEngine.so'
'/opt/qtc/415/lib/Qt/lib/libQt5WebEngine.so.5' 
'/opt/qtc/415/lib/Qt/lib/libQt5WebEngine.so.5.15'
'/opt/qtc/415/lib/Qt/lib/libQt5WebEngine.so.5.15.2' 
'/opt/qtc/415/lib/Qt/lib/libQt5WebEngineCore.la' 
'/opt/qtc/415/lib/Qt/lib/libQt5WebEngineCore.prl' 
'/opt/qtc/415/lib/Qt/lib/libQt5WebEngineCore.so' 
'/opt/qtc/415/lib/Qt/lib/libQt5WebEngineCore.so.5' 
'/opt/qtc/415/lib/Qt/lib/libQt5WebEngineCore.so.5.15' 
'/opt/qtc/415/lib/Qt/lib/libQt5WebEngineCore.so.5.15.2' 
'/opt/qtc/415/lib/Qt/lib/libQt5WebEngineWidgets.la' 
'/opt/qtc/415/lib/Qt/lib/libQt5WebEngineWidgets.prl' 
'/opt/qtc/415/lib/Qt/lib/libQt5WebEngineWidgets.so'
'/opt/qtc/415/lib/Qt/lib/libQt5WebEngineWidgets.so.5' 
'/opt/qtc/415/lib/Qt/lib/libQt5WebEngineWidgets.so.5.15'
'/opt/qtc/415/lib/Qt/lib/libQt5WebEngineWidgets.so.5.15.2'  
```

libexec stuff:
`'/opt/qtc/415/lib/Qt/libexec/QtWebEngineProcess'`

resources:
```'/opt/qtc/415/lib/Qt/resources/icudtl.dat'
'/opt/qtc/415/lib/Qt/resources/qtwebengine_devtools_resources.pak'
'/opt/qtc/415/lib/Qt/resources/qtwebengine_resources.pak'
'/opt/qtc/415/lib/Qt/resources/qtwebengine_resources_100p.pak'
'/opt/qtc/415/lib/Qt/resources/qtwebengine_resources_200p.pak'
```

**Comment by francescmaestre** [comment]
Hi @FoxTrot75 @isgursoy I'll try to take a look into it soon. I didn't released a new plugin yet since I'm still thinking if I should include the new GitHub and Jenkins integrations.

**Comment by isgursoy** [comment]
I am looking forward to replace my GitKraken subscription with the GitQlient
subscription, hopefully soon.

Writing this comment in Qt Creator, by GitQlient.

**Comment by francescmaestre** [comment]
@isgursoy Niiiiiiiice to see that! :smile: Do you know that GitQlient is a standalone app as well, right?

https://github.com/francescmm/GitQlient

**Comment by isgursoy** [comment]
Yeah but it's greatness that makes me fall in love with it is Qt Creator integration. But yes, It is still -almost- as good as GitKraken as a standalone app.

**Comment by francescmaestre** [comment]
Off-topic: @isgursoy could you open a ticket with those things you miss from GitKraken that are not in GitQlient? (or that you like more from there)

**Comment by isgursoy** [comment]
Sure, as soon as possible. Today, differences in favor of GitKraken are just a few and I think you are already planning many of those.

**Comment by foxtrot75** [comment]
Sorry, I use QtCreator with mingw on Windows 10.
I don't have MSVC compiler, and don't use it.
I tried build your plugin for my system with your build script, but got lots of errors.

**Comment by francescmaestre** [comment]
Hi @FoxTrot75 I've done a release with the Windows 10 version of the plugin: https://github.com/francescmm/GitQlientPlugin/releases/tag/v1.4.0
